# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0076_airecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='survey.Record')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('language', models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'fr', 'French')], default='en', max_length=7)),
                ('further_comments', models.TextField(blank=True, help_text="Observations that might be relevant but don't fit elsewhere", verbose_name='Further comments')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Follow-up form answered')),
            ],
            options={
                'verbose_name': 'HRD Case Follow-Up',
            },
        ),
    ]
