# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_followup_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Follow-up processed'),
        ),
    ]
