# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_followup_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='followup', serialize=False, to='survey.Record'),
        ),
    ]
