# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20170317_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'fr', 'French')], default='en', max_length=7),
        ),
    ]
