# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20170317_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='attention',
            field=models.IntegerField(choices=[(1, 'Definitely not'), (2, 'Rather not'), (3, 'Probably'), (4, 'For sure'), (6, "I don't know")], default=None, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='contact_again',
            field=models.BooleanField(default=False, verbose_name='You can contact me again if you have further questions about this case'),
        ),
        migrations.AddField(
            model_name='followup',
            name='email_address',
            field=models.EmailField(blank=True, default=None, help_text="please note that by submitting your email address, your contact will be known by and can be connected to this case by the independent researcher carrying out the analysis. If you don't indicate your contact details, your submission will remain anonymous", max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='followup',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Details about impact'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_date_1',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of incident #1'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_date_2',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of incident #2'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_date_3',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of incident #3'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_date_4',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of incident #4'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_date_5',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of incident #5'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_text_1',
            field=models.TextField(blank=True, verbose_name='Brief description of incident #1'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_text_2',
            field=models.TextField(blank=True, verbose_name='Brief description of incident #2'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_text_3',
            field=models.TextField(blank=True, verbose_name='Brief description of incident #3'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_text_4',
            field=models.TextField(blank=True, verbose_name='Brief description of incident #4'),
        ),
        migrations.AddField(
            model_name='followup',
            name='incident_text_5',
            field=models.TextField(blank=True, verbose_name='Brief description of incident #5'),
        ),
        migrations.AddField(
            model_name='followup',
            name='want_informed',
            field=models.BooleanField(default=False, verbose_name='I want to be informed about the outcome of this study'),
        ),
    ]
