# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20170321_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='familiarity',
            field=models.IntegerField(choices=[(1, 'I am very familiar with the case.'), (2, 'I have information but it might be incomplete.'), (3, 'I only have little information.'), (4, "I don't have any information.")], default=4, null=True),
        ),
    ]
