# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_followup_familiarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='internal_comments',
            field=models.TextField(blank=True, verbose_name='Internal comments'),
        ),
    ]
