# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_followup_internal_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='attention',
            field=models.IntegerField(choices=[(1, 'For sure'), (2, 'Probably'), (3, 'Rather not'), (4, 'Definitely not'), (6, "I don't know")], default=6, null=True),
        ),
    ]
