# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_auto_20170323_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='familiarity',
            field=models.IntegerField(choices=[(1, 'I am very familiar with the case.'), (2, 'I have information but it might be incomplete.'), (3, 'I only have little information.'), (4, "I don't have any information.")], default=4, null=True, verbose_name='Level of familiarity'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_1',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_2',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_3',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_4',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_5',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'es', 'Spanish'), (b'fr', 'French')], default='en', max_length=7, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Much better'), (2, 'Somewhat better'), (3, 'Situation stayed the same overall'), (4, 'Somewhat worse'), (5, 'Much worse'), (6, "I don't know")], default=6, null=True, verbose_name='Rating'),
        ),
    ]
