# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20170324_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='intervention',
            field=models.IntegerField(choices=[(1, 'For sure'), (2, 'Probably'), (3, 'Rather not'), (4, 'Definitely not'), (6, "I don't know")], default=6, null=True, verbose_name='Impact of intervention'),
        ),
    ]
