# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_followup_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='attention',
            field=models.IntegerField(choices=[(1, 'Definitely yes'), (2, 'Probably'), (3, 'Probably not'), (4, 'Definitely not'), (6, 'I do not know')], default=6, null=True, verbose_name='Impact of international attention'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='familiarity',
            field=models.IntegerField(choices=[(1, 'I am very familiar with the case.'), (2, 'I have information but it might be incomplete.'), (3, 'I only have little information.'), (4, 'I do not have any information.')], default=4, null=True, verbose_name='Level of familiarity'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='further_comments',
            field=models.TextField(blank=True, verbose_name='Any additional comments/feedback'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='intervention',
            field=models.IntegerField(choices=[(1, 'Definitely yes'), (2, 'Probably'), (3, 'Probably not'), (4, 'Definitely not'), (6, 'I do not know')], default=6, null=True, verbose_name='Impact of intervention'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Much better'), (2, 'Somewhat better'), (3, 'Situation stayed the same overall'), (4, 'Somewhat worse'), (5, 'Much worse'), (6, 'I do not know')], default=6, null=True, verbose_name='Rating'),
        ),
    ]
