# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20170331_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Much better'), (2, 'Somewhat better'), (3, 'Situation stayed the same overall'), (4, 'Somewhat worse'), (5, 'Much worse'), (7, 'There were equally important positive and negative developments'), (6, 'I do not know')], default=6, null=True, verbose_name='Rating'),
        ),
    ]
