# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20170331_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='attention',
            field=models.IntegerField(choices=[(1, 'Definitely yes'), (2, 'Probably yes'), (3, 'Probably not'), (4, 'Definitely not'), (6, 'I do not know')], default=6, null=True, verbose_name='Impact of international attention'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='intervention',
            field=models.IntegerField(choices=[(1, 'Definitely yes'), (2, 'Probably yes'), (3, 'Probably not'), (4, 'Definitely not'), (6, 'I do not know')], default=6, null=True, verbose_name='Impact of intervention'),
        ),
    ]
