# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_auto_20170401_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='incident_date_1',
            field=models.CharField(blank=True, help_text='Format YYYY-MM-DD', max_length=100, null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_2',
            field=models.CharField(blank=True, help_text='Format YYYY-MM-DD', max_length=100, null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_3',
            field=models.CharField(blank=True, help_text='Format YYYY-MM-DD', max_length=100, null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_4',
            field=models.CharField(blank=True, help_text='Format YYYY-MM-DD', max_length=100, null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='incident_date_5',
            field=models.CharField(blank=True, help_text='Format YYYY-MM-DD', max_length=100, null=True, verbose_name='Date of the incident'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='language',
            field=models.CharField(choices=[(b'en', b'English'), (b'es', b'Espa\xc3\xb1ol'), (b'fr', b'Fran\xc3\xa7ais')], default='en', max_length=7, verbose_name='Language'),
        ),
    ]
