# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20170402_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='internal_edit',
            field=models.BooleanField(default=False, verbose_name='Internally edited'),
        ),
        migrations.AddField(
            model_name='followup',
            name='internal_submit',
            field=models.BooleanField(default=False, verbose_name='Internally submitted'),
        ),
    ]
