# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import select_multiple_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(help_text='Form YYYY-CCC-P, where YYYY is the year of publication, CCC is the sequential communcation number, and P the person number within the communication', max_length=10, verbose_name='Person ID')),
                ('name', models.CharField(max_length=500)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Not Male')])),
                ('issue_area', select_multiple_field.models.SelectMultipleField(choices=[('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/Forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/Refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-Corruption'), ('?', 'N/A')], default='?', help_text='Select maximum 2 items', max_choices=2, max_length=10)),
                ('relevant_activities', select_multiple_field.models.SelectMultipleField(choices=[('L', 'Lawyer'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('S', 'Student'), ('J', 'Journalist/Editor/Writer'), ('MP', 'Medical professional'), ('T', 'Teacher/Professor'), ('CL', 'Community leader'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference'), ('PP', 'Participation in protest/rally'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items', max_choices=3, max_length=15)),
                ('international_cooperation', models.IntegerField(choices=[(0, 'Not mentioned'), (1, 'UN'), (2, 'INGO')], default=0)),
                ('follow_up_case', models.BooleanField(default=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('location', models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('?', 'Unknown')], default='?', max_length=1)),
                ('name_area', models.CharField(blank=True, max_length=500, verbose_name='Name of City / Area')),
                ('violations', select_multiple_field.models.SelectMultipleField(choices=[('AD', 'Arrest/Detention'), ('P', 'Prosecution'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('K', 'Killing'), ('KA', 'Killing attempt/Assault'), ('DI', 'Diappearance/Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('T', 'Threats'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('B', 'Barred from travelling'), ('AH', 'Administrative harassment'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items', max_choices=3, max_length=15, verbose_name='Violation(s)')),
                ('violation_family', models.IntegerField(choices=[(0, 'Only HDR'), (1, 'against relative'), (2, 'against both')], default=0, verbose_name='Violation against family member')),
                ('perpetrator', models.CharField(choices=[('P', 'Police/Security forces'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown'), ('?', 'N/A')], default='?', max_length=2, verbose_name='Alleged perpetrator')),
                ('date_incident', models.DateField(blank=True, null=True, verbose_name='Date of the latest incident')),
                ('date_intervention', models.DateField(blank=True, null=True, verbose_name='Date of the intervention')),
                ('type_intervention', models.CharField(choices=[('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], max_length=3, verbose_name='Type of intervention')),
                ('joint_with', models.CharField(blank=True, choices=[('FREX', 'FREX'), ('TOR', 'TOR')], max_length=4, null=True)),
                ('concern_expressed', models.CharField(choices=[('PM', 'Protection measures'), ('II', 'Independent investigation'), ('PI', 'Provide information'), ('PV', 'Concern: Pattern of violation'), ('CV', 'Concern over violation')], max_length=2, verbose_name='Concern expressed / demand')),
                ('date_govreply', models.DateField(blank=True, help_text='Date, leave empty for "No response"', null=True, verbose_name='Date of government reply')),
                ('government_reply_content', models.CharField(choices=[('reject', 'Violation rejected'), ('incomp', 'Reponsive but incomplete'), ('immat', 'Immaterial response'), ('react', 'Steps taken to address')], help_text='According to rating criteria by Piccone (2012)', max_length=6, verbose_name='Content of government reply')),
                ('date_government_action', models.DateField(blank=True, null=True, verbose_name='Date of government action according to reply')),
                ('government_reply_action', models.CharField(choices=[('protect', 'Protection measures granted'), ('release', 'Individual released'), ('improve', 'Improved prison conditions'), ('investigate', 'Investigation opened'), ('prosecuted', 'Perpetrator suspended/prosecuted'), ('issued', 'Travel documents issued')], max_length=11, verbose_name='Government action taken accroding to reply')),
                ('further_comments', models.TextField(blank=True, help_text="Observations that might be relevant but don't fit elsewhere", verbose_name='Further comments')),
            ],
        ),
    ]
