# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 20:29
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=django_countries.fields.CountryField(default='DE', max_length=2),
            preserve_default=False,
        ),
    ]
