# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date_government_action',
            new_name='date_govaction',
        ),
        migrations.RemoveField(
            model_name='record',
            name='government_reply_action',
        ),
        migrations.RemoveField(
            model_name='record',
            name='government_reply_content',
        ),
        migrations.AddField(
            model_name='record',
            name='govreply_action',
            field=models.CharField(blank=True, choices=[('protect', 'Protection measures granted'), ('release', 'Individual released'), ('improve', 'Improved prison conditions'), ('investigate', 'Investigation opened'), ('prosecuted', 'Perpetrator suspended/prosecuted'), ('issued', 'Travel documents issued')], max_length=11, verbose_name='Government action taken accroding to reply'),
        ),
        migrations.AddField(
            model_name='record',
            name='govreply_content',
            field=models.CharField(blank=True, choices=[('reject', 'Violation rejected'), ('incomp', 'Reponsive but incomplete'), ('immat', 'Immaterial response'), ('react', 'Steps taken to address')], help_text='According to rating criteria by Piccone (2012)', max_length=6, verbose_name='Content of government reply'),
        ),
        migrations.AddField(
            model_name='record',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=survey.models.update_filename),
        ),
    ]
