# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160525_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='concern_expressed',
            field=models.CharField(blank=True, choices=[('CV', 'Concern over violation'), ('PM', 'Protection measures'), ('II', 'Independent investigation'), ('PI', 'Provide information'), ('PV', 'Concern: Pattern of violation')], max_length=2, verbose_name='Concern expressed / demand'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_govaction',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of government action according to reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_govreply',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD, leave empty for "No response"', null=True, verbose_name='Date of government reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_incident',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of the latest incident'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_intervention',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of the intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Trans/inter*')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/Forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/Refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-Corruption'), ('?', 'N/A')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('L', 'Lawyer'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('S', 'Student'), ('J', 'Journalist/Editor/Writer'), ('MP', 'Medical professional'), ('T', 'Teacher/Professor'), ('CL', 'Community leader'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference'), ('PP', 'Participation in protest/rally'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='type_intervention',
            field=models.CharField(choices=[('NA', 'N/A'), ('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], max_length=3, verbose_name='Type of intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violation_family',
            field=models.IntegerField(choices=[(0, 'Only HRD'), (1, 'against relative'), (2, 'against both')], default=0, verbose_name='Violation against HRD or family member?'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('AD', 'Arrest/Detention'), ('P', 'Prosecution'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('K', 'Killing'), ('KA', 'Killing attempt/Assault'), ('DI', 'Diappearance/Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('T', 'Threats'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('B', 'Barred from travelling'), ('AH', 'Administrative harassment'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Violation(s)'),
        ),
    ]
