# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_record_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='toppings',
            field=select_multiple_field.models.SelectMultipleField(choices=[('a', 'Anchovies'), ('b', 'Black olives'), ('p', 'Pepperoni'), ('m', 'Mozzarella')], default='m', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('O', 'Not Male'), ('?', 'Unknown')], default='?', max_length=1),
        ),
    ]
