# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 15:58
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20160526_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/Forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/Refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-Corruption'), ('PV', 'Police violence')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=10),
        ),
    ]
