# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:28
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20160523_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/Forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/Refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-Corruption'), ('NA', 'N/A')], default='NA', max_choices=3, max_length=50),
            preserve_default=False,
        ),
    ]
