# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20160529_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='further_info',
            field=models.TextField(blank=True, help_text='Name of NGO or party, title of conference, object of investigation etc.', verbose_name='Further information'),
        ),
        migrations.AddField(
            model_name='record',
            name='ohchr_case',
            field=models.CharField(blank=True, max_length=20, verbose_name='OHCHR case no.'),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=models.CharField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='perpetrator',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('P', 'Police/security forces'), ('CS', 'Civil servant/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=2, verbose_name='Alleged perpetrator'),
        ),
    ]
