# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20160529_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='concern_expressed',
            field=models.CharField(blank=True, choices=[('CV', 'Concern over violation'), ('PM', 'Protection measures'), ('II', 'Independent investigation'), ('PI', 'Provide information'), ('PV', 'Concern: Pattern of violation')], max_length=2, verbose_name='Concern/demand expressed in intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name of HRD'),
        ),
    ]
