# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:30
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20160523_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('L', 'Lawyer'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('S', 'Student'), ('J', 'Journalist/Editor/Writer'), ('MP', 'Medical professional'), ('T', 'Teacher/Professor'), ('CL', 'Community leader'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference'), ('PP', 'Participation in protest/rally'), ('?', 'N/A')], default='?', max_choices=3, max_length=50),
        ),
    ]
