# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20160529_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_intervention',
	    field=models.DateField(default='1970-01-01', help_text='Format YYY-MM-DD', verbose_name='Date of the intervention'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=models.CharField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR')], max_length=10, null=True),
        ),
    ]
