# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20160523_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='intl_coop',
            field=models.CharField(choices=[('U', 'UN'), ('I', 'INGO'), ('?', 'Not mentioned')], default='?', max_length=1),
        ),
    ]
