# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_record_intl_coop'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='followup',
            field=models.BooleanField(default=False),
        ),
    ]
