# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:13
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20160530_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('L', 'Lawyer'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('S', 'Student'), ('J', 'Journalist/Editor/Writer'), ('MP', 'Medical professional'), ('T', 'Teacher/Professor'), ('CL', 'Community leader'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference'), ('PP', 'Participation in protest/rally'), ('OP', 'Ombudsperson')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15),
        ),
    ]
