# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20160523_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name_of_city_or_area',
            field=models.CharField(default='?', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('AD', 'Arrest/Detention'), ('P', 'Prosecution'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('K', 'Killing'), ('KA', 'Killing attempt/Assault'), ('DI', 'Diappearance/Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('T', 'Threats'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('B', 'Barred from travelling'), ('AH', 'Administrative harassment'), ('?', 'N/A')], default='?', max_choices=3, max_length=15),
        ),
    ]
