# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20160531_1120'),
        ('survey', '0012_auto_20160531_1116'),
    ]

    operations = [
    ]
