# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20160523_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('?', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='name_of_city_or_area',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
