# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20160523_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='violation_against_family_member',
            field=models.CharField(choices=[(0, 'Only HDR'), (1, 'against relative'), (2, 'against both')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
