# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_record_violation_against_family_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('?', 'Unknown')], default='?', max_length=1),
        ),
    ]
