# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20160531_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person_id',
            field=models.CharField(help_text='Form YYYY-CCC-P, where YYYY is the year of publication, CCC is the paragraph number given in the report, and P the person number within the communication', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10, message=None)], verbose_name='Person ID'),
        ),
    ]
