# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20160601_1327'),
        ('survey', '0017_auto_20160601_1345'),
    ]

    operations = [
    ]
