# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20160523_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='international_cooperation',
            field=models.IntegerField(choices=[(0, 'Not mentioned'), (1, 'UN'), (2, 'INGO')], default=0),
        ),
    ]
