# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20160601_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='govreply_action',
            field=models.CharField(blank=True, choices=[('protect', 'Protection measures granted'), ('release', 'Individual released early'), ('improve', 'Improved prison conditions'), ('investigate', 'Investigation opened'), ('prosecuted', 'Perpetrator suspended/prosecuted'), ('issued', 'Travel documents issued')], max_length=11, verbose_name='Government action taken according to reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='govreply_content',
            field=models.CharField(blank=True, choices=[('reject', 'Violation rejected'), ('incomp', 'Reponsive but incomplete'), ('immat', 'Immaterial response'), ('react', 'Steps taken to address'), ('transl', 'In translation')], help_text='According to rating criteria by Piccone (2012)', max_length=6, verbose_name='Content of government reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-corruption'), ('PV', 'Police violence'), ('DV', 'Democratic/voting rights'), ('TJ', 'Transitional justice'), ('POV', 'Poverty')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=10),
        ),
    ]
