# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20160601_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='regional_case',
            field=models.BooleanField(default=False, verbose_name='Regional mechanism case'),
        ),
        migrations.AlterField(
            model_name='record',
            name='follow_up_case',
            field=models.BooleanField(default=False, verbose_name='Follow-up on UN case'),
        ),
    ]
