# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20160523_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date_of_birth',
            new_name='date_intervention',
        ),
        migrations.AddField(
            model_name='record',
            name='alleged_perpetrator',
            field=models.CharField(choices=[('P', 'Police/Security forces'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown'), ('?', 'N/A')], default='?', max_length=2),
        ),
        migrations.AddField(
            model_name='record',
            name='date_latest_incident',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='type_intervention',
            field=models.CharField(choices=[('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], default='PR', max_length=3),
            preserve_default=False,
        ),
    ]
