# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20160523_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='concern_expressed',
            field=models.CharField(choices=[('PM', 'Protection measures'), ('II', 'Independent investigation'), ('PI', 'Provide information'), ('PV', 'Concern: Pattern of violation'), ('CV', 'Concern over violation')], default='PM', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='joint_with',
            field=models.CharField(choices=[('FREX', 'FREX'), ('TOR', 'TOR')], default='FREX', max_length=4),
            preserve_default=False,
        ),
    ]
