# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20160523_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=models.CharField(choices=[('FREX', 'FREX'), ('TOR', 'TOR')], max_length=4, null=True),
        ),
    ]
