# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:28
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20160612_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='perpetrator2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('P', 'Police/security forces'), ('CS', 'Civil servant/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=10, verbose_name='Alleged perpetrator'),
        ),
        migrations.AddField(
            model_name='record',
            name='perpetrator3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('P', 'Police/security forces'), ('CS', 'Civil servant/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown')], default='?', help_text='Select maximum 2 items with <i>Ctrl+Click</i>', max_choices=2, max_length=10, verbose_name='Alleged perpetrator'),
        ),
        migrations.AddField(
            model_name='record',
            name='violations2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('DI', ' + Kidnapping'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Violation(s)'),
        ),
        migrations.AddField(
            model_name='record',
            name='violations3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('DI', ' + Kidnapping'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Violation(s)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('DI', ' + Kidnapping'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Violation(s)'),
        ),
    ]
