# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20160523_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='branch',
        ),
        migrations.AddField(
            model_name='record',
            name='person_id',
            field=models.CharField(default='2000-001-01', max_length=10),
            preserve_default=False,
        ),
    ]
