# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_auto_20160523_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='alleged_perpetrator',
        ),
        migrations.RemoveField(
            model_name='record',
            name='date_latest_incident',
        ),
        migrations.RemoveField(
            model_name='record',
            name='violation_against_family_member',
        ),
        migrations.AddField(
            model_name='record',
            name='date_incident',
            field=models.DateField(blank=True, null=True, verbose_name='Date of the latest incident'),
        ),
        migrations.AddField(
            model_name='record',
            name='perpetrator',
            field=models.CharField(choices=[('P', 'Police/Security forces'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('U', 'Unknown'), ('?', 'N/A')], default='?', max_length=2, verbose_name='Alleged perpetrator'),
        ),
        migrations.AddField(
            model_name='record',
            name='violation_family',
            field=models.IntegerField(choices=[(0, 'Only HDR'), (1, 'against relative'), (2, 'against both')], default=0, verbose_name='Violation against family member'),
        ),
    ]
