# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20160612_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='concern_expressed',
            field=models.CharField(blank=True, choices=[('CV', 'Concern over violation'), ('PV', 'Concern: Pattern of violation'), ('PM', 'Demand: Protection measures'), ('II', 'Demand: Independent investigation'), ('PI', 'Demand: Provide information'), ('RD', 'Demand: Release detainee')], max_length=2, verbose_name='Concern/demand expressed in intervention'),
        ),
    ]
