# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20160523_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name_of_city_or_area',
        ),
        migrations.AddField(
            model_name='record',
            name='name_area',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name of City / Area'),
        ),
    ]
