# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20160523_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='government_reply_content',
            field=models.CharField(choices=[('reject', 'Violation rejected'), ('incomp', 'Reponsive but incomplete'), ('immat', 'Immaterial response'), ('react', 'Steps taken to address')], help_text='According to rating criteria by Piccone (2012)', max_length=6, verbose_name='Content of government reply'),
        ),
    ]
