# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20160612_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
