# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20160523_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_govreply',
            field=models.DateField(blank=True, help_text='Date, leave empty for "No response"', null=True, verbose_name='Date of government reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='further_comments',
            field=models.TextField(blank=True, help_text="Observations that might be relevant but don't fit elsewhere", verbose_name='Further comments'),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('WR', "Women's rights"), ('LGBTI', 'LGBTI issues'), ('IPR', "Indigenous peoples' rights"), ('HRFE', 'Housing rights/Forced evictions'), ('LNR', "Land rights/nat' res'/environment"), ('LR', 'Labour rights'), ('IF', 'Internet freedom'), ('CRS', "Children's rights"), ('HI', 'Health issues'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('HRE', 'Human rights education'), ('MRR', "Migrants'/Refugees' rights"), ('MR', 'Minority rights (if not specified)'), ('AT', 'Anti-Torture'), ('PR', "Prisoner's rights"), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('AC', 'Anti-Corruption'), ('?', 'N/A')], default='?', help_text='Select maximum 2 items', max_choices=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='person_id',
            field=models.CharField(help_text='Form YYYY-CCC-P, where YYYY is the year of publication, CCC is the sequential communcation number, and P the person number within the communication', max_length=10, verbose_name='Person ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('L', 'Lawyer'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('S', 'Student'), ('J', 'Journalist/Editor/Writer'), ('MP', 'Medical professional'), ('T', 'Teacher/Professor'), ('CL', 'Community leader'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference'), ('PP', 'Participation in protest/rally'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items', max_choices=3, max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('AD', 'Arrest/Detention'), ('P', 'Prosecution'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('K', 'Killing'), ('KA', 'Killing attempt/Assault'), ('DI', 'Diappearance/Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('T', 'Threats'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('B', 'Barred from travelling'), ('AH', 'Administrative harassment'), ('?', 'N/A')], default='?', help_text='Select maximum 3 items', max_choices=3, max_length=15, verbose_name='Violation(s)'),
        ),
    ]
