# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20160614_1547'),
        ('survey', '0033_auto_20160612_2327'),
    ]

    operations = [
    ]
