# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_auto_20160614_1612'),
        ('survey', '0038_merge'),
    ]

    operations = [
    ]
