# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0038_auto_20160614_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'HRD Record'},
        ),
    ]
