# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import re
import select_multiple_field.models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20160615_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='Form YYYY-CCCC-P, where YYYY is the year of publication and CCCC the paragraph number given in the report', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9, message=None)], verbose_name='Case ID')),
                ('ohchr_case', models.CharField(blank=True, max_length=20, verbose_name='OHCHR case no.')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_intervention', models.DateField(help_text='Format YYY-MM-DD', verbose_name='Date of the intervention')),
                ('type_intervention', models.CharField(choices=[('?', 'N/A'), ('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], max_length=3, verbose_name='Type of intervention')),
                ('joint_with', select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200)),
                ('name', models.CharField(max_length=500, verbose_name='Name of NGO')),
                ('follow_up_case', models.BooleanField(default=False, verbose_name='Follow-up on UN case')),
                ('regional_case', models.BooleanField(default=False, verbose_name='Regional mechanism case')),
                ('further_comments', models.TextField(blank=True, help_text="Observations that might be relevant but don't fit elsewhere", verbose_name='Further comments')),
                ('upload', models.FileField(blank=True, null=True, upload_to=survey.models.update_filename)),
            ],
            options={
                'verbose_name': 'NGO Record',
            },
        ),
    ]
