# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_auto_20160615_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='case_id',
            field=models.CharField(help_text='Form YYYY-CCCC, where YYYY is the year of publication and CCCC the paragraph number given in the report', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(9, message=None)], verbose_name='Case ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='person_id',
            field=models.CharField(help_text='Form YYYY-CCCC-PP, where YYYY is the year of publication, CCCC is the paragraph number given in the report, and PP the person number within the communication', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12, message=None)], verbose_name='Person ID'),
        ),
    ]
