# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_auto_20160615_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='feedback',
            field=models.TextField(blank=True, help_text='Direct feedback on the coding of this particular case', verbose_name='Feedback'),
        ),
    ]
