# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0043_record_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecord',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text='User responsible for this record', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analyst'),
        ),
        migrations.AddField(
            model_name='record',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text='User responsible for this record', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analyst'),
        ),
    ]
