# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 15:44
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_auto_20160618_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='coords',
            field=djgeojson.fields.PointField(blank=True, editable=False, null=True),
        ),
    ]
