# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_record_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='govreply_action',
            field=models.CharField(blank=True, choices=[('protect', 'Protection measures granted'), ('release', 'Individual released early'), ('notrial', 'Individual released without trial'), ('improve', 'Improved prison conditions'), ('investigate', 'Investigation opened'), ('prosecuted', 'Perpetrator suspended/prosecuted'), ('issued', 'Travel documents issued')], max_length=11, verbose_name='Action taken according to reply'),
        ),
    ]
