# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 08:25
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_auto_20160809_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
    ]
