# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0049_auto_20160816_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Final'),
        ),
    ]
