# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0052_auto_20160923_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='international_cooperation',
            field=models.IntegerField(choices=[(0, 'Not mentioned'), (1, 'UN'), (2, 'INGO/other IO')], default=0),
        ),
    ]
