# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0055_auto_20160923_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='earlier_coms',
            field=models.CharField(blank=True, max_length=500, verbose_name='Date(s) of earlier coms'),
        ),
    ]
