# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0056_record_earlier_coms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_intervention',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', verbose_name='Date of the intervention'),
        ),
    ]
