# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 21:02
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0058_auto_20160926_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('WR', "Women's rights"), ('CRS', "Children's rights"), ('IPR', "Indigenous peoples' rights"), ('LGBTI', 'LGBTI issues'), ('MRR', "Migrants'/refugees'/IDP's rights"), ('MR', "Ethnic minorities' rights"), ('LR', 'Labour rights'), ('POV', 'Poverty'), ('RTF', 'Right to food/water'), ('HI', 'Health issues'), ('RE', 'Right to education'), ('HRFE', 'Housing rights/forced evictions'), ('LNR', 'Land rights/environment'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('PR', "Prisoner's rights"), ('AT', 'Torture'), ('DP', 'Death penalty'), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('PV', 'Police/military violence'), ('NSV', 'Non-state violence'), ('AC', 'Corruption'), ('DV', 'Democratic/voting rights'), ('IF', 'Internet freedom'), ('HRE', 'Human rights education'), ('TJ', 'Transitional justice'), ('PA', 'Peace activism'), ('AR', 'Anti-racism')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='perpetrator',
            field=select_multiple_field.models.SelectMultipleField(choices=[('U', 'Unknown'), ('P', 'Police/security forces'), ('CS', 'Public official/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('PM', 'Paramilitary group'), ('PP', 'Private person')], default='U', help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=10, verbose_name='Alleged perpetrator'),
        ),
        migrations.AlterField(
            model_name='record',
            name='perpetrator2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('U', 'Unknown'), ('P', 'Police/security forces'), ('CS', 'Public official/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('PM', 'Paramilitary group'), ('PP', 'Private person')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=10, verbose_name='Alleged perpetrator #2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='perpetrator3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('U', 'Unknown'), ('P', 'Police/security forces'), ('CS', 'Public official/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('PM', 'Paramilitary group'), ('PP', 'Private person')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=10, verbose_name='Alleged perpetrator #3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('CL', 'Community leader'), ('L', 'Lawyer/Judge/Attorney'), ('J', 'Journalist/Editor'), ('CA', 'Cyberactivist'), ('A', 'Artist/Writer'), ('S', 'Student'), ('T', 'Teacher/Professor/Scientist'), ('MP', 'Medical professional'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('OP', 'Ombudsperson/Procuraduria/NHRI'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference/meeting'), ('PP', 'Participation in public protest/rally')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('DI', 'Kidnapping'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], default='?', help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('DI', 'Kidnapping'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', ' + Incommunicado'), ('PC', ' + Held in poor conditions'), ('RT', ' + Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', ' + Killing attempt'), ('K', '  + Killing'), ('DI', 'Kidnapping'), ('P', 'Prosecution'), ('UT', ' + Unfair trial'), ('C', ' + Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #3'),
        ),
    ]
