# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-04 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0059_auto_20161004_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='foreign_national',
            field=models.BooleanField(default=False, verbose_name='Foreign national'),
        ),
    ]
