# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0060_record_foreign_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_intervention',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of the intervention'),
        ),
    ]
