# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0062_auto_20161012_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('A', 'Abroad'), ('?', 'Unknown')], default='?', max_length=1),
        ),
    ]
