# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 16:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0071_auto_20161108_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person_id',
            field=models.CharField(help_text='Form YYYY-CCCC-PPP, where YYYY is the year of publication, CCCC is the paragraph number given in the report, and PPP the person number within the communication', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\-\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(13, message=None)], verbose_name='Person ID'),
        ),
    ]
