# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0073_auto_20161123_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Trans/inter*'), (3, 'Gender unclear')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='govreply_action',
            field=models.CharField(blank=True, choices=[('protect', 'Protection measures granted'), ('release', 'Individual released early'), ('notrial', 'Individual released without trial'), ('improve', 'Improved prison conditions'), ('investigate', 'Investigation opened'), ('prosecuted', 'Perpetrator suspended/prosecuted'), ('issued', 'Travel documents issued'), ('other', 'Other')], max_length=11, verbose_name='Action taken according to reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('CL', 'Community leader'), ('L', 'Lawyer/Judge/Attorney'), ('J', 'Journalist/Editor'), ('CA', 'Cyberactivist'), ('A', 'Artist/Writer'), ('S', 'Student'), ('T', 'Teacher/Professor/Scientist'), ('MP', 'Medical professional'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('OP', 'Ombudsperson/Procuraduria/NHRI'), ('UN', 'UN official'), ('GAS', 'Government/Army/Security forces'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference/meeting'), ('PP', 'Participation in public protest/rally')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15),
        ),
    ]
