# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-31 16:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0075_auto_20161128_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(default='AI-', help_text='Form AI-YYYY-RRRR-PPP, where YYYY is the year of publication, RRRR is the reference, and PPP the person number within the communication', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16, message=None)], verbose_name='Person ID')),
                ('ai_reference', models.CharField(max_length=25, verbose_name='AI Internal Reference')),
                ('pub_reference', models.CharField(blank=True, max_length=25, verbose_name='Public ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('date_submission', models.DateField(help_text='Format YYY-MM-DD', verbose_name='Date of the submission')),
                ('joint_with', select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Additional mandates')),
                ('name', models.CharField(max_length=500, verbose_name='Name of HRD')),
                ('case_summary', models.TextField(blank=True, verbose_name='Case Summary')),
                ('fa_title', models.TextField(blank=True, verbose_name='FA Title')),
                ('fa_date', models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of FA')),
                ('fa_summary', models.TextField(blank=True, verbose_name='Summary of FA')),
                ('fa_title2', models.TextField(blank=True, verbose_name='FA Title (2)')),
                ('fa_date2', models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of FA (2)')),
                ('fa_summary2', models.TextField(blank=True, verbose_name='Summary of FA (2)')),
                ('fa_title3', models.TextField(blank=True, verbose_name='FA Title (3)')),
                ('fa_date3', models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of FA (3)')),
                ('fa_summary3', models.TextField(blank=True, verbose_name='Summary of FA (3)')),
                ('fa_title4', models.TextField(blank=True, verbose_name='FA Title (4)')),
                ('fa_date4', models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Date of FA (4)')),
                ('fa_summary4', models.TextField(blank=True, verbose_name='Summary of FA (4)')),
                ('further_comments', models.TextField(blank=True, help_text="Observations that might be relevant but don't fit elsewhere", verbose_name='Further comments')),
                ('is_final', models.BooleanField(default=False, verbose_name='Final')),
                ('analyst', models.ForeignKey(blank=True, help_text='User responsible for this record', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Analyst')),
            ],
            options={
                'verbose_name': 'AI Record',
            },
        ),
    ]
