# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0076_airecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='affiliation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Affiliation'),
        ),
        migrations.AddField(
            model_name='record',
            name='sources_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Number of sources'),
        ),
        migrations.AddField(
            model_name='record',
            name='sources_type',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('NGO', 'NGO'), ('RNGO', 'RNGO'), ('LNGO', 'LNGO'), ('GOV', 'GOV'), ('IO', 'IO'), ('IND', 'Indiv.')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Type of sources'),
        ),
    ]
