# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0077_auto_20170314_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='follow_ups',
            field=models.ManyToManyField(default=None, related_name='_record_follow_ups_+', to='survey.Record', verbose_name='Follow-up Person IDs'),
        ),
    ]
