# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0079_auto_20170317_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='follow_ups',
        ),
    ]
