# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0080_remove_record_follow_ups'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='complaint_received',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Complaint received on'),
        ),
        migrations.AddField(
            model_name='record',
            name='complaint_sent',
            field=models.DateField(blank=True, help_text='Format YYY-MM-DD', null=True, verbose_name='Complaint sent on'),
        ),
    ]
