# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 18:40
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0081_auto_20170319_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sources_type',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('NGO', 'INGO'), ('RNGO', 'RNGO'), ('LNGO', 'LNGO'), ('GOV', 'GOV'), ('IO', 'IO'), ('IND', 'Indiv.')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Type of sources'),
        ),
    ]
