# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import djgeojson.fields
import select_multiple_field.models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0083_auto_20170320_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Joint with'),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=survey.models.update_filename, verbose_name='Uploads'),
        ),
        migrations.AlterField(
            model_name='record',
            name='coords',
            field=djgeojson.fields.PointField(blank=True, editable=False, null=True, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='record',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='record',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Trans/inter*'), (3, 'Gender unclear')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='record',
            name='international_cooperation',
            field=models.IntegerField(choices=[(0, 'Not mentioned'), (1, 'UN'), (2, 'INGO/other IO')], default=0, verbose_name='International cooperation'),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('WR', "Women's rights"), ('CRS', "Children's rights"), ('IPR', "Indigenous peoples' rights"), ('LGBTI', 'LGBTI issues'), ('MRR', "Migrants'/refugees'/IDP's rights"), ('MR', "Ethnic minorities' rights"), ('LR', 'Labour rights'), ('POV', 'Poverty/social welfare'), ('RTF', 'Right to food/water'), ('HI', 'Health issues'), ('RE', 'Right to education'), ('HRFE', 'Housing rights/forced evictions'), ('LNR', 'Land rights/environment'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('PR', "Prisoner's rights"), ('AT', 'Torture'), ('DP', 'Death penalty'), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('PV', 'Police/military violence'), ('NSV', 'Non-state violence'), ('AC', 'Corruption'), ('DV', 'Democratic/voting rights'), ('JI', 'Judicial independence'), ('IF', 'Internet freedom'), ('HRE', 'Human rights education'), ('TJ', 'Transitional justice'), ('PA', 'Peace activism'), ('AR', 'Anti-racism'), ('RP', 'Right to privacy')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=20, verbose_name='Issue area'),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Joint with'),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('A', 'Abroad'), ('?', 'Unknown')], default='?', max_length=1, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('CL', 'Community leader'), ('L', 'Lawyer/Judge/Attorney'), ('J', 'Journalist/Editor'), ('CA', 'Cyberactivist'), ('A', 'Artist/Writer'), ('S', 'Student'), ('T', 'Teacher/Professor/Scientist'), ('MP', 'Medical professional'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('OP', 'Ombudsperson/Procuraduria/NHRI'), ('UN', 'UN official'), ('GAS', 'Government/Army/Security forces'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference/meeting'), ('PP', 'Participation in public protest/rally')], default='?', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Relevant activities'),
        ),
        migrations.AlterField(
            model_name='record',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=survey.models.update_filename, verbose_name='Uploads'),
        ),
    ]
