# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0084_auto_20170324_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecord',
            name='date_submission',
            field=models.DateField(help_text='Format YYYY-MM-DD', verbose_name='Date of the submission'),
        ),
        migrations.AlterField(
            model_name='airecord',
            name='fa_date',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of FA'),
        ),
        migrations.AlterField(
            model_name='airecord',
            name='fa_date2',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of FA (2)'),
        ),
        migrations.AlterField(
            model_name='airecord',
            name='fa_date3',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of FA (3)'),
        ),
        migrations.AlterField(
            model_name='airecord',
            name='fa_date4',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of FA (4)'),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='date_intervention',
            field=models.DateField(help_text='Format YYYY-MM-DD', verbose_name='Date of the intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='complaint_received',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Complaint received on'),
        ),
        migrations.AlterField(
            model_name='record',
            name='complaint_sent',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Complaint sent on'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_govaction',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of action according to reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_govreply',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD, leave empty for "No response"', null=True, verbose_name='Date of government reply'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_incident',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the latest incident'),
        ),
        migrations.AlterField(
            model_name='record',
            name='date_intervention',
            field=models.DateField(blank=True, help_text='Format YYYY-MM-DD', null=True, verbose_name='Date of the intervention'),
        ),
    ]
