# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 15:01
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0085_auto_20170324_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='perpetrator4',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('U', 'Unknown'), ('P', 'Police/security forces'), ('CS', 'Public official/administration/judiciary'), ('A', 'Army'), ('AO', 'Armed opposition'), ('B', 'Business/landholder'), ('M', 'Mob'), ('PM', 'Paramilitary group'), ('PP', 'Private person'), ('RA', 'Religious authority')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=10, verbose_name='Alleged perpetrator #4'),
        ),
        migrations.AddField(
            model_name='record',
            name='violations4',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #4'),
        ),
    ]
