# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 17:03
from __future__ import unicode_literals

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0086_auto_20170530_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('PRIVACY', 'PRIVACY'), ('DEBT', 'DEBT'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Additional mandates'),
        ),
        migrations.AlterField(
            model_name='otherrecord',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('PRIVACY', 'PRIVACY'), ('DEBT', 'DEBT'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Joint with'),
        ),
        migrations.AlterField(
            model_name='record',
            name='joint_with',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('FrASSEM', 'FrASSEM'), ('FrEXPRESS', 'FrEXPRESS'), ('TORTURE', 'TORTURE'), ('WGAD', 'WGAD'), ('WGED', 'WGED'), ('SumEXECU', 'SumEXECU'), ('WOMEN', 'WOMEN'), ('FrRELIGION', 'FrRELIGION'), ('JUDGES', 'JUDGES'), ('INDIGENOUS', 'INDIGENOUS'), ('TERRORISM', 'TERRORISM'), ('BUSINESS', 'BUSINESS'), ('HEALTH', 'HEALTH'), ('ENVIR', 'ENVIR'), ('FOOD', 'FOOD'), ('CHILD', 'CHILD'), ('RACISM', 'RACISM'), ('HOUSING', 'HOUSING'), ('MINORITY', 'MINORITY'), ('EDUCATION', 'EDUCATION'), ('MIGRANTS', 'MIGRANTS'), ('WASTE', 'WASTE'), ('IDPs', 'IDPs'), ('WG_WOMEN', 'WG_WOMEN'), ('MERCENARIES', 'MERCENARIES'), ('TRUTH', 'TRUTH'), ('POVERTY', 'POVERTY'), ('CULTURE', 'CULTURE'), ('ELDERLY', 'ELDERLY'), ('SLAVERY', 'SLAVERY'), ('WATER', 'WATER'), ('AFRICAN', 'AFRICAN'), ('DISCAPA', 'DISCAPA'), ('SOLIDAR', 'SOLIDAR'), ('INTORDER', "INT'ORDER"), ('TRAFFIC', 'TRAFFIC'), ('PRIVACY', 'PRIVACY'), ('DEBT', 'DEBT'), ('specific', 'Country-specific')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=200, verbose_name='Joint with'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect'), ('CR', 'Citizenship revoked')], default='?', help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect'), ('CR', 'Citizenship revoked')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect'), ('CR', 'Citizenship revoked')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations4',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('?', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect'), ('CR', 'Citizenship revoked')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #4'),
        ),
    ]
