# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0086_auto_20170530_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecord',
            name='type_intervention',
            field=models.CharField(choices=[('X', 'N/A'), ('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], max_length=3, verbose_name='Type of intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_area',
            field=select_multiple_field.models.SelectMultipleField(choices=[('X', 'N/A'), ('WR', "Women's rights"), ('CRS', "Children's rights"), ('IPR', "Indigenous peoples' rights"), ('LGBTI', 'LGBTI issues'), ('MRR', "Migrants'/refugees'/IDP's rights"), ('MR', "Ethnic minorities' rights"), ('LR', 'Labour rights'), ('POV', 'Poverty/social welfare'), ('RTF', 'Right to food/water'), ('HI', 'Health issues'), ('RE', 'Right to education'), ('HRFE', 'Housing rights/forced evictions'), ('LNR', 'Land rights/environment'), ('CR', 'Cultural rights'), ('RF', 'Religious freedom'), ('PR', "Prisoner's rights"), ('AT', 'Torture'), ('DP', 'Death penalty'), ('ED', 'Enforced disappearance'), ('H', 'Homocide'), ('PV', 'Police/military violence'), ('NSV', 'Non-state violence'), ('AC', 'Corruption'), ('DV', 'Democratic/voting rights'), ('JI', 'Judicial independence'), ('IF', 'Internet freedom'), ('HRE', 'Human rights education'), ('TJ', 'Transitional justice'), ('PA', 'Peace activism'), ('AR', 'Anti-racism'), ('RP', 'Right to privacy')], default='X', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=20, verbose_name='Issue area'),
        ),
        migrations.AlterField(
            model_name='record',
            name='location',
            field=models.CharField(choices=[('C', 'Capital'), ('T', 'City/Town'), ('R', 'Rural area'), ('A', 'Abroad'), ('X', 'Unknown')], default='X', max_length=1, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relevant_activities',
            field=select_multiple_field.models.SelectMultipleField(choices=[('X', 'N/A'), ('CSA', 'Civil society activist'), ('TUA', 'Trade union activist'), ('RA', 'Religious association'), ('PM', 'Politician/Party member'), ('CL', 'Community leader'), ('L', 'Lawyer/Judge/Attorney'), ('J', 'Journalist/Editor'), ('CA', 'Cyberactivist'), ('A', 'Artist/Writer'), ('S', 'Student'), ('T', 'Teacher/Professor/Scientist'), ('MP', 'Medical professional'), ('HW', 'Humanitarian worker'), ('V', 'Victim/witness of HR violations'), ('OP', 'Ombudsperson/Procuraduria/NHRI'), ('UN', 'UN official'), ('GAS', 'Government/Army/Security forces'), ('I', 'Investigation against officials'), ('PC', 'Participation in conference/meeting'), ('PP', 'Participation in public protest/rally')], default='X', help_text='Select maximum 3 items with <i>Ctrl+Click</i>', max_choices=3, max_length=15, verbose_name='Relevant activities'),
        ),
        migrations.AlterField(
            model_name='record',
            name='type_intervention',
            field=models.CharField(choices=[('X', 'N/A'), ('UA', 'UA'), ('JUA', 'JUA'), ('AL', 'AL'), ('JAL', 'JAL'), ('PR', 'PR')], max_length=3, verbose_name='Type of intervention'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations',
            field=select_multiple_field.models.SelectMultipleField(choices=[('X', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], default='X', help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations2',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('X', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #2'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations3',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('X', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #3'),
        ),
        migrations.AlterField(
            model_name='record',
            name='violations4',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('X', 'N/A'), ('AD', 'Arrest/Detention'), ('IC', 'Incommunicado'), ('PC', 'Held in poor conditions'), ('RT', 'Risk of torture'), ('TI', 'Torture/Ill-treatment'), ('ED', 'Enforced disappearance'), ('KA', 'Physical attack'), ('KK', 'Killing attempt'), ('K', 'Killing'), ('DI', 'Kidnapping'), ('P', 'Trial'), ('UT', 'Unfair trial'), ('C', 'Conviction'), ('T', 'Threats'), ('S', 'Surveillance'), ('R', 'Office/home raided'), ('PD', 'Property stolen/confiscated/destroyed'), ('DC', 'Defamation campaign'), ('DP', 'Disciplinary proceedings'), ('B', 'Travel restrictions'), ('A', 'Access denied'), ('VD', 'Expulsion/Visa denied'), ('AH', 'Administrative harassment'), ('FI', 'Failure to intervene/protect')], help_text='Select multiple items with <i>Ctrl+Click</i>', max_length=50, verbose_name='Violation(s) #4'),
        ),
    ]
