#!/bin/bash

NAME="datacollect"                                # Name of the application
DJANGODIR=/home/django/dc/datacollect                # Django project directory
SOCKFILE=/home/django/dc/gunicorn.sock               # we will communicte using this unix socket
USER=django                                       # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=datacollect.settings_production
DJANGO_WSGI_MODULE=datacollect.wsgi               # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --bind=unix:$SOCKFILE \
  --timeout=300 \
  --log-level=debug \
  --log-file=/home/django/dc/logs/gunicorn.log

#  --user=$USER --group=$GROUP \
